<div class="row padded-bottom">
	<img src="/images/about-us-banner.jpg" alt="Color Compass Corporation Leadership Team">
</div>
<div class="row small-up-1 large-up-2 bio">
	<div class="column rh-1">
		<h4>Chris (Sumio) Kikuchi<br>Chief Executive Officer</h4>
		<p><img src="/images/hs-sumio.jpg" alt="Chris (Sumio) Kikuchi" title="Chris (Sumio) Kikuchi">Chris (Sumio) Kikuchi is the C.E.O. of the Color Compass Corporation, Chris' business career began very shortly after his graduation from Japan’s Nippon University in 1978 when he began to work in his father’s many and varied businesses. In the succeeding years Chris travelled the world extensively visiting and working in almost every inhabited continent before settling in Vancouver in 1979. Once in Vancouver Chris quickly acted  to open the Canadian branch of his Father's real estate acquisition and management business. In 1984 Chris purchased White &amp; Peters Ltd. and Mutual Warehouses, (known today as PBE Distributors Inc.), this was Chris’ first Canadian experience with the distribution business and as history has shown has been a very positive one. In the years that followed, Chris continued to expand and grow the business both organically and through acquisition. Three years later in 1987, Carlson Body Shop Supply and PBE Distributors in Alberta were acquired and a new PBE warehouse was opened in Ontario a few years after that. In 1997, Chase Auto Body Supplies in Manitoba and Saskatchewan was acquired and welcomed into the Color Compass family. To date through the acquisitions mentioned and others which were consolidated into the existing operating companies Chris, through his vision and guidance, has grown the Color Compass Corporation into the preeminent supplier of collision repair products and services to the Automotive Refinish Industry.</p>
	</div>
	<div class="column rh-1">
		<h4>Rob Neale<br>President &amp; Chief Operating Officer</h4>
		<p><img src="/images/hs-rob.jpg" alt="Rob Neale" title="Rob Neale">Rob Neale is the President and Chief Operating Officer of the Color Compass Corporation. Rob is responsible for all facets of the organization including finance and strategic direction. Rob joined the company on a part time summer basis in 1972 and was promoted rapidly through the ranks; it was at this point he decided not to return to college. Throughout the next ten years Rob expanded his experience, from delivery driver, to warehousing, to inside counter sales and then, with some financial and purchasing training moved into a purchasing role. In 1982 Rob was promoted to General Operations Manager. Four years later, in late 1986, the new owner Mr. Chris Kikuchi wanted to expand through acquisition, it was only natural from both a geographical and business model perspective to begin negotiations with Carlson Body Shop Supply Ltd. and PBE Distributors Inc. in Alberta. Negotiations concluded July 1, 1987 with Rob moving to Edmonton, Alberta as Vice President of the Color Compass Corporation. After 5 years of successfully growing the business and integrating the new acquisition into the corporate model Rob moved back to B.C. as Group Vice President and Chief Operating Officer. In 2006 after several years of continual growth both organically and through strategic acquisitions, Rob was promoted to President of a larger and certainly more complex organization than his start in 1972. Rob's overall vision; that strong relationships (non-financial partnerships) with both valued customers and strategic partners has been immensely rewarding, both personally and professionally and has served the Color Compass Corporation quite well.</p>
	</div>
	<div class="column rh-2">
		<h4>Gord Milford<br>Executive Vice President</h4>
		<p><img src="/images/hs-gord.jpg" alt="Gord Milford" title="Gord Milford">Gord Milford is the Executive Vice President of the Color Compass Corporation, overseeing all of the groups operating companies and corporate departments. Gord works closely with each division, driving topline revenue while always focusing on a strong profitable bottom line. Gord has recently worked closely with the leadership team in creating a sales, marketing and operational vision for the Color Compass Corporation's bright future. Gord joined Color Compass in 1983 as a delivery driver in Edmonton Alberta with Carlson Body Shop Supply, moving through various positions before being transferred to Calgary to start the sales team of a new PBE Distributors location in 1987. In 1990 Gord was then transferred to southern Ontario to open and manage another new PBE location. Three short years later in 1993 Gord was transferred back to Edmonton and appointed General Manager of Carlson’s and became a part of what would be a strong growth period for the group. With the Color Compass acquisition of Chase Auto Body Supplies in 1997, while still at the helm of Carlson Body Shop Supply, Gord was then selected to oversee the transition and manage the newly acquired company. Gord was appointed to his current position of Vice President in 2006 and as in the past is still focused on growth, innovation, and what's next for the group.</p>
	</div>
	<div class="column rh-2">
		<h4>Mort Hall<br>General Manager, White &amp; Peters Ltd.</h4>
		<p><img src="/images/hs-mort.jpg" alt="Mort Hall" title="Mort Hall">As General Manager Mort Hall is tasked with overseeing the sales, operations, and financial management of White &amp; Peters ltd, and brings to this position over 40 years of industry experience. In 1974 Mort joined White &amp; Peters working as a service technician in the Vancouver branch through till 1981. Following that, over the next three years Mort moved into the role of Inside Sales and Customer Service. In 1984 Mort was promoted to the role of Branch Manager of the Richmond and New Westminster locations and accepted the role of Operations Manager of White &amp; Peters shortly after in 1986. Five short years later, in 1991, Mort was promoted to his current position of General Manager.</p>
	</div>
	<div class="column">
		<h4>Dave Swenson<br>General Manager, Carlson Body Shop Supply Ltd.</h4>
		<p><img src="/images/hs-dave.jpg" alt="Dave Swenson" title="Dave Swenson">Based in the Edmonton office, Dave Swenson oversees the day to day operations of Carlson Body Shop Supply. He is active in leading his team of sales and business development managers throughout Alberta and Saskatchewan. Dave's focus with his team is to analyze strategic markets, devise growth targets and ensure profitability through smart fiscal control. In his 38 years with the company Dave has held many positions with the Color Compass group, most within the sales function.</p>
	</div>
	<div class="column">
		<h4>Tim Shay<br>General Manager, Chase Auto Body Supplies Ltd.</h4>
		<p><img src="/images/hs-tim.jpg" alt="Tim Shay" title="Tim Shay">As General Manager of Chase Auto Body Supplies, Tim Shay is charged with overseeing the sales, financial performance, and operations of the company throughout Western Canada. Tim is based in the Winnipeg office and brings to this position over 25 years of experience as an Operations, Sales and General Manager. Tim began his career as a driver at Chase and progressed through the ranks of the organization before being named General Manager in June 2002. Tim brings with him many prior years in management and leadership roles.
		</p>
	</div>
	<div class="column rh-4">
		<h4>Arnie White<br>General Manager, PBE Distributors Inc.</h4>
		<p><img src="/images/hs-arnie.jpg" alt="Arnie White" title="Arnie White" class="line-pad">Arnie White is the General Manager of PBE Distributors and has been with the group since 1973. As General Manager Arnie is tasked with overseeing the sales and profitability of PBE Distributors, and also plays a large role in vendor negotiations and new product line acquisitions. Arnie started in 1973 as a delivery driver for White &amp; Peters in Vancouver. Moving through various roles over the next few years, in 1977, Arnie was promoted into a sales role with the warehouse division of the group, then Mutual Warehouse (PBE Distributors Inc.). Through Arnie’s direction he has overseen the growth of PBE Distributors from one warehouse location in Vancouver to where it is today with five throughout Canada servicing 27 Color Compass locations.</p>
	</div>
	<div class="column rh-4">
		<h4>Teuta (Tia) Hoti<br>Chief Financial Officer</h4>
		<p><img src="/images/hs-tia.jpg" alt="Tia Hoti" title="Tia Hoti">As Chief Financial Officer of the Color Compass Corporation Tia Hoti oversees the overall accounting and finance functions of the company. Tia and her team are responsible for the financial reporting, transparency, planning, analysis, treasury, internal audit and control for the group. She joined Color Compass in 2004 as an Intermediate Accountant, in 2006 she became Controller of the company and in November 2013 she was appointed Chief Financial Officer. Tia holds a Bachelor Degree in Accounting &amp; Finance and has 25 years of experience in building and leading accounting teams, cost benefit analysis, cash flow and forecasting needs, M&amp;A, budget management and business support.</p>
	</div>
	<div class="column">
		<h4>Jim Coxford<br>Director of Purchasing</h4>
		<p><img src="/images/hs-jim.jpg" alt="Jim Coxford" title="Jim Coxford">As Director of Purchasing, Jim's brings to his position over 35 years of industry experience at various levels, of which 26 years with the Color Compass Corporation. Jim is located in the south Edmonton office and his responsibilities include overseeing the procurement of inventory goods, vendor negotiations and the inventory management for 17 locations, including 27 branches, as well as many other aspects of the business. In addition, Jim and his team work closely with all managers of the group to ensure the ultimate goal of customer satisfaction is achieved.</p>
	</div>
	<div class="column">
		<h4>Emile Fremont<br>Director of Business Development</h4>
		<p><img src="/images/hs-emile.jpg" alt="Emile Fremont" title="Emile Fremont">Based in Calgary, Emile Fremont's primary role includes the development and implementation of Color Compass Corporations suite of value added initiatives. Emile brings to his position over 30 years of industry experience in operations, sales, and management. Originally based in the Edmonton office, he has worked throughout Western Canada before settling in Calgary. Emile also holds a diploma in Business Administration from Southern Alberta Institute of Technology Polytechnic.</p>
	</div>
	<div class="column">
		<h4>Geoff Neale<br>Director of Operations</h4>
		<p><img src="/images/hs-geoff.jpg" alt="Geoff Neale" title="Geoff Neale">Based in the Coquitlam office, Geoff Neale is responsible for overseeing and maximizing the respective operations of the companies within the Color Compass group across Canada. Geoff brings to this position over 18 years of experience working in multiple roles throughout the various operating companies. Geoff started off as a driver and worked in various managerial and analysis roles before being named Director of Operations in 2014. Geoff has studied business management through BCIT, and operations and supply chain management through APICS.</p>
	</div>
	<div class="column">
		<h4>Brent Dutka<br>Credit Manager</h4>
		<p><img src="/images/hs-brent.jpg" alt="Brent Dutka" title="Brent Dutka">Brent Dutka's experience working in the automotive refinishing field spans more than 36 years including working in service and sales with White &amp; Peters before moving into the accounting department in 1987. Upon receiving his CCP designation from the University of Toronto in 1994 Brent became the Credit Manager for the Color Compass Corporation. Prior to joining Color Compass Brent worked in the Engineering Department for the City of Vancouver.</p>
	</div>
	<div class="column rh-7">
		<h4>Chris Neale<br>Director of Marketing</h4>
		<p><img src="/images/hs-chris.jpg" alt="Chris Neale" title="Chris Neale">Chris Neale is based in the Coquitlam office and is tasked with overseeing the group's internal and external marketing, branding and promotional activities. Chris actively works with each company within the Color Compass group to support their sales goals, while creating continuity between each division. Chris has been with the company for 15 years and has held many positions in that time; from inside sales and customer service to outside sales and business development. Chris studied business management and marketing at the British Columbia Institute of Technology in Vancouver.</p>
	</div>
	<div class="column rh-7">
		<h4>Carmen Stanciulescu<br>IT Systems Architect</h4>
		<p><img src="/images/hs-carmen.jpg" alt="Carmen Stanciulescu" title="Carmen Stanciulescu">Carmen is responsible for leadership and direction on the support and development of new and existing IT systems for Color Compass Corporation. Applying a broad range of information technology, business planning, administration experience and knowledge, Carmen provides the technical direction to redesign business processes, translate business needs into requirement specifications, and assess opportunities for application of technologies. Carmen has a degree in Computer Science and 25 years of experience in designing, programming and implementing ERP systems, as well as architectural design of systems integration to satisfy both internal and external customers and vendor's needs.</p>
	</div>
</div>