<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Grid Your Way To Paradise Two Rules</title>
		<link href="/css/normalize.css" rel="stylesheet" type="text/css">
		<link href="/css/foundation.min.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="row">
			<div class="column text-center" id="logo"><img src="/images/logo.png" alt="Color Compass Corporation" /></div>
			<div class="small-12 column">
				<h3>Color Compass &quot;Grind Your Way to Paradise 2&quot; Official Contest Rules</h3>
				<p>General Terms and Definitions Used in the Rules<br>
					General Description of the Contest<br>
					Contest Eligibility<br>
					How to Obtain a Contest Entry without Making a Purchase<br>
					Transfers<br>
					How To Play<br>
					Prizes, Prize Limitations and the Chances of Winning<br>
					Selection of Contest Winners</p>
				<p>THE COLOR COMPASS &quot;Grind Your Way To Paradise 2&quot; CONTEST (THE &quot;CONTEST&quot;) IS INTENDED TO BE CONDUCTED IN THE PROVINCES OF BC, ALBERTA, SASKATCHEWAN, AND MANITOBA ONLY. NO PURCHASE IS NECESSARY. PARTICIPANTS MUST BE 19 YEARS OF AGE OR OLDER. VOID IN WHOLE OR PART WHERE PROHIBITED BY LAW. ENTRY IN THIS CONTEST CONSTITUTES ACCEPTANCE OF THESE CONTEST RULES (THE &quot;CONTEST RULES&quot;). </p>
				<p><strong>1. ELIGIBILITY.</strong> This Contest is open to individuals who are a resident in Alberta, Saskatchewan, Manitoba and British Columbia, or having businesses that are currently and legally registered corporations, partnerships, proprietors or other enterprises in Alberta, Saskatchewan, Manitoba and B.C.</p>
				<p>Employees of  the Color Compass Corporation and 3M Canada (collectively, the "Sponsors"), their respective affiliates, subsidiaries, related companies, advertising and promotional agencies, and the household members or immediate family of any of the above, are not eligible to participate in the Contest. In these Contest Rules, "immediate family" means husband, wife, spouse, mother, father, brothers, sisters, sons and daughters, whether or not they reside in the same household.</p>
				<p>The Sponsors shall have the right at any time to require proof of identity and/or eligibility to participate in the Contest. Failure to provide such proof may result in disqualification. All personal and other information requested by and supplied to the Sponsors for the purpose of the Contest must be truthful, complete, accurate and in no way misleading. The Sponsors reserve the right, in their sole discretion, to disqualify any entrant should such an entrant at any stage be in breach of the Contest Rules or supply untruthful, incomplete, inaccurate or misleading personal details and/or information.</p>
				<p><strong>2. CONTEST PERIOD.</strong> The Contest begins at 5:00 a.m. Pacific Time on Tuesday November 1st, 2016 and ends at 11:59 p.m PST Tuesday, January 31st, 2016 (the "Contest Period") after which time the Contest will be closed and no further entries will be awarded.</p>
				<p><strong>3. HOW TO ENTER.</strong></p>
				<p>(a) There is no purchase necessary to enter the Contest.</p>
				<p><strong>(i) Customer Entry details:</strong> </p>
				<p><strong>Color Compass Corporation and its companies (Carlson Body Shop Supply, Chase Auto Body Supplies, Rocky Mountain Sales ltd, and White & Peters ltd. will award one entry for every $200 purchased (excluding tax) of 3M Cubitorn II & select Accuspray Products and the Paint Defect Removal System stocking products.</strong></p>
				<p><strong>(ii) Backorders - All backorders as of the last day of the promotion (January 31st, 2016) will be counted as purchases towards entries.</strong></p>
				<p><strong>(iii) No Purchase Entry details: </strong> </p>
				<p>For a no purchase entry ballot, complete and submit a 500 word no-purchase entry ballot (a &quot;No Purchase Necessary Ballot Essay&quot;) essay describing your thoughts on self driving vehicles and when we'll begin to see them. Only one entry per household is permitted. Entrants, who submit more than one official entry, or more than one entry per household, will be disqualified. Please mail entries to "Grind Your Way 2" Color Compass Corporation, #202-1368 United Blvd, Coquitlam, BC, V3K 6Y2.</p>
				<p>(b) All entries become the sole property of Color Compass Corporation and none will be returned for any reason. Entries must be received no later than the end of the Contest Deadline. Entries will be declared invalid if they are late, illegible, incomplete, damaged, irregular, mutilated, forged, garbled or mechanically or electronically reproduced. No communication or correspondence will be exchanged with entrants except with those selected for a Prize.</p>
				<p>(d) Entries submitted by mail must be received by Color Compass Corporation as noted above no later than the end of the Contest Deadline, and must be in a separate outer envelope bearing sufficient postage.</p>
				<p><strong>4. PRIZES.</strong></p>
				<p>(a) There is one (1) "Grand Prize".  The Grand Prize is a $3,500 travel voucher in Canadian funds. The Voucher must be used with Fernweh Travel Vancouver, located in Vancouver BC. The voucher will not be redeemable as cash. </p>
				<p>(b) The prize must be accepted as awarded. No transfers, substitutions, exchanges or monetary reimbursements are allowed. The Prize winner is responsible for any and all expenses associated with their prize. The Sponsors are not responsible for any delay, postponement, suspension, rescheduling or cancellation, for any reason, of the awarding of any Prize and prize winners will not be compensated in the event of such delay, cancellation or other event described herein. Other restrictions may apply.</p>
				<p>(c) Guests must comply with the Contest Rules and sign and return the Release (described below).</p>
				<p>(d) The Sponsors shall not assume any liability for lost, damaged or misdirected entries.</p>
				<p><strong>5. WINNER SELECTION.</strong></p>
				<p>The winner will be selected by way of a random draw on the night of February 8th, 2017, in Coquitlam, BC</p>
				<p>THE SELECTED WINNER WILL BE NOTIFIED BY PHONE AND MUST RESPOND WITHIN FIVE (5) BUSINESS DAYS OF NOTIFICATION. The winner will be attempted to be contacted twice on consecutive days, and no voicemail or other messages are required to be provided by Sponsors.  If not contacted by such means or the selected winner does not strictly comply with the Contest Rules, he/she will be disqualified and will not receive a prize, and either the alternative winner will then be notified, or it not applicable, another winner will be selected from the either the original eligible pools of entries, or from the entire pool of entries for all prizes. If after three such attempts to determine a winner the Sponsors have not identified and contacted a winner, the Sponsors reserve the right to award the prize (or its cash equivalent) to the alternative winners selected, or upon failure to contact such alternatives, to a charity of their choice. Sponsors are not responsible for the failure for any reason whatsoever of selected a winner to receive notification or for Sponsors to receive a selected winner’s response.</p>
				<p>The odds of being selected as a potential winner are dependant upon the number of eligible entries received by the Sponsors. Before being declared a winner, the selected entrant will be required to correctly answer, without assistance of any kind, whether mechanical or otherwise, a time-limited mathematical skill-testing question, comply with the Contest Rules, and sign and return the Release (described below).</p>
				<p>The Sponsors reserve the right, in its sole and absolute discretion, and without prior notice, to adjust any of the dates and/or timeframes stipulated in these Contest Rules, to the extent necessary, for purposes of verifying compliance by any entrant or Entry with these Contest Rules, or as a result of any problems, or in light of any other circumstances which, in the opinion of the Sponsors, in their sole and absolute discretion, affect the proper administration of the Contest as contemplated in these Contest Rules, or for any other reason.</p>
				<p><strong>6. RELEASE. </strong>The winner will be required to execute a legal agreement and release (&quot;Release&quot;) that confirms winner's: (i) eligibility for the Contest and compliance with these Contest Rules; (ii) acceptance of the Prize as offered; (iii) release of each of the Sponsors and their respective parent companies, subsidiaries, affiliates and/or related companies and each of their employees, directors, officers, suppliers, agents, sponsors, administrators, licensees, representatives, advertising, media buying and promotional agencies (collectively, the &quot;Releasees&quot;) from any and all liability for any loss, harm, damages, cost or expense arising out of participation in the Contest, participation in any Contest-related activity or the acceptance, use, or misuse of any Prize, including but not limited to costs, injuries, losses related to personal injuries, death, damage to, loss or destruction of property, rights of publicity or privacy, defamation, or portrayal in a false light, or from any and all claims of third parties arising therefrom; and: (iv) grant to the Sponsors of the unrestricted right, in the Sponsors' collective or individual discretion, to produce, reproduce, publish, broadcast, communicate by telecommunication, exhibit, distribute, adapt and otherwise use or re-use the winner's name, photograph and  likeness, in any and all media now known or hereafter devised, in connection with the Contest and the promotion and exploitation thereof. The executed Release must be returned within five (5) business days of the verification as a winner or the selected entrant will be disqualified and the Prize forfeited.</p>
				<p><strong>7. INDEMNIFICATION BY ENTRANT.</strong> By entering the Contest, entrant (a) releases and holds harmless Sponsors and their respective directors, officers, employees, parent companies, subsidiaries, affiliates, suppliers, sponsors and agents from any and all liability for any injuries, loss or damage of any kind to the Applicant or any other person, including personal injury, death, or property damage, resulting in whole or in part, directly or indirectly, from acceptance, possession, use or misuse of any Prize, participation in this Contest, any breach of these Contest Rules, or in any prize-related activity; and (b) agrees to fully indemnify Sponsors and their respective directors, officers, employees, parent companies, subsidiaries, affiliates, suppliers, sponsors and agents from any and all claims by third parties relating to the Contest, without limitation.</p>
				<p><strong>8. LIMITATION OF LIABILITY.</strong> The Sponsors are not responsible for any incorrect or inaccurate information, whether caused by any of the equipment or programming associated with or utilized in the Contest or by any technical or human error which may occur in the administration of the Contest. The Sponsors assume no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, entries. The Sponsors are not responsible for any problems, failures or technical malfunction of any telephone network or lines, on account of technical problems or otherwise. The Sponsors are not responsible for any injury or damage to entrant related to or resulting from participating in this Contest. Entrant assumes liability for injuries caused or claimed to be caused by participating in the Contest, or by the acceptance, possession, use of, or failure to receive any Prize. The Sponsors assume no responsibility or liability in the event that the Contest cannot be conducted as planned for any reason, including those reasons beyond the control of the Sponsors, such as tampering, unauthorized intervention, fraud, technical failures, or corruption of the administration, security, fairness, integrity or proper conduct of this Contest. </p>
				<p><strong>9. CONDUCT.</strong> By participating in the Contest, each entrant agrees to be bound by the Contest Rules. Entrant further agrees to be bound by the decisions of the Sponsors, which shall be final and binding in all respects. The Sponsors reserve the right, in their sole discretion, to disqualify any entrant found to be: (a) violating the Contest Rules; (b) tampering or attempting to tamper with the entry process or the operation of the Contest the Contest Website; and/or (c) acting in an unsportsmanlike or disruptive manner, or with intent to annoy, abuse, threaten or harass any other person.</p>
				<p><strong>10. PRIVACY / USE OF PERSONAL INFORMATION.</strong> </p>
				<p>(a) By participating in the Contest, the entrant: (i) grants to the Sponsors the right to use his/her name, mailing address, telephone number, and e-mail address (&quot;Personal Information&quot;) for the purpose of administering the Contest, including but not limited to contacting and announcing the winners; (ii) grants to the Sponsors the right to use his/her Personal Information, and his or her name, photograph, likeness, voice, prize information and/or biographical information, for publicity and promotional purposes relating to the Contest, on the Contest Website and other websites in print, or any other media, or in any and all media now known or hereafter devised, without further compensation unless prohibited by law.</p>
				<p>(b) The Sponsors will use the entrant's Personal Information only for identified purposes, and protect the entrant's Personal Information in a manner that is consistent with the Color Compass Corporation’s Privacy Policy.</p>
				<p><strong>11. INTELLECTUAL PROPERTY.</strong> All intellectual property, including but not limited to trade-marks, trade names, logos, designs, promotional materials, web pages, source code, drawings, illustrations, slogans and representations are owned by the Sponsors and/or their affiliates. All rights are reserved. Unauthorized copying or use of any copyrighted material or intellectual property without the express written consent of its owner is strictly prohibited.</p>
				<p><strong>12. TERMINATION.</strong> The Sponsors reserve the right, in their sole discretion, to terminate the Contest, in whole or in part, and/or modify, amend or suspend the Contest, and/or the Contest Rules in any way, at any time, for any reason without prior notice.</p>
				<p><strong>13. LAW.</strong> These are the official Contest Rules. The Contest is subject to applicable federal, provincial and municipal laws and regulations. The Contest Rules are subject to change without notice in order to comply with any applicable federal, provincial and municipal laws or the policy of any other entity having jurisdiction over the Sponsors. All issues and questions concerning the construction, validity, interpretation and enforceability of the Contest Rules or the rights and obligations as between the entrant and the Sponsors in connection with the Contest shall be governed by and construed in accordance with the laws of the provinces including procedural provisions without giving effect to any choice of law or conflict of law rules or provisions that would cause the application of any other jurisdiction's laws.</p>
				<p><strong>14. LANGUAGE DISCREPANCY.</strong> In the event of any discrepancy or inconsistency between the terms and conditions of the Contest Rules and disclosures or other statements contained in any Contest-related materials, including but not limited to the Contest entry form, or point of sale, print or online advertising, the terms and conditions of the Contest Rules shall prevail, govern and control.</p>
				<p><strong>15. FOR RESIDENTS OF QUEBEC:</strong> This contest is not open to residents of Quebec.</p>
			</div>
		</div>
	</body>
</html>