		<div class="row padded-bottom">
			<img src="/images/about-us-banner.jpg" alt="Color Compass History">
		</div>
		<div class="row">
			<div class="small-12 column padded-vertical">
				<h3>Our History</h3>
				<p>The Color Compass Corporation is the largest independent automotive refinishes and related auto body supplies distributor in Canada. The growth of the company is a celebration of innovation, opportunity, and acquisition.</p>
				<p>In 1984 Color Compass was founded with the acquisition of both White &amp; Peters and Mutual Warehouse in British Columbia. With an eye on expansion and growth in Western Canada, Color Compass moved into Alberta with the acquisition of Carlson Body Shop Supply and PBE Distributors in 1987. Over the next ten years the group would consolidate Mutual Warehouse within PBE Distributors and further strengthen the already strong Carlson's brand in Edmonton and Calgary. In 1997 the growth continued with the group’s largest acquisition to date with the purchase of Chase Auto Body Supplies in Winnipeg, Manitoba. As in the past, Color Compass further expanded its distribution network by opening a PBE Distributors warehouse location in Winnipeg at that time as well. With an eye on further strengthening its position in British Columbia and Alberta, 2006 and 2007 saw the acquisitions of Valley Car Colour in Langley BC, and Rocky Mountain Sales in Edmonton.</p>
				<p>In 2011 the Color Compass Corporation finalized what would become a pivotal moment in the group's strong presence in Western Canada, with the acquisition of the corporate Akzo Nobel jobber stores in Alberta and British Columbia. With the acquisition, Chase Auto Body Supplies moved west, growing both in terms of size and talent, keeping a sharp focus on expanding their new markets within Alberta and British Columbia.</p>
				<p>Color Compass traces its roots back to 1959 in Edmonton, Alberta, where the group's oldest company, Carlson Body Shop Supply was founded by Bill Carlson. Three years later in Vancouver, British Columbia White &amp; Peters was founded by Jim White and Walt Peters in 1962. One year after that, in 1963, Cy Chase founded Chase Auto Body Supplies in Winnipeg, Manitoba. In an effort to further expand their distribution network as well as increase their buying power Jim White &amp; Walt Peters founded Mutual Warehouse (now PBE Distributors) in 1968. To this day each of the group's companies was founded on the core principal of trusted relationships and excellent customer service. Although the automotive collision repair industry has changed immensely over the years, at the core of each of the Color Compass companies is still excellent customer service, rooted in strong relationships.</p>
				<p>Through the years the Color Compass Corporation has grown to a team of over 265 dedicated staff operating within 27 locations throughout Canada.</p>
				<a href="/images/ccc_timeline.png" target="_blank"><img src="/images/ccc_timeline.png" alt="Color Compass Corporation Timeline"></a>
			</div>
		</div>
