<div class="news">
	<h5>5Star Products are Ours!</h5>
	<div class="image text-center">
		<img src="/images/news/5star-xtreme.png" alt="5star Xtreme">
	</div>
	<p>Every so often our attention is drawn to a product offering in our company for a variety of reasons. Reasons for this focus could be growth, lack of growth, new products, agency representation change. One particular line that has been almost under the radar while achieving steady growth and market penetration year after year is an offering from Autobody Brands. What started out just over twenty years ago as the 5-Star Brand has now grown into four separate brands; 5-Star, Advantage, Duragloss and Pure Reflections.</p>
	<p>The 5-Star line is celebrating its 25th anniversary in the US has been sold through our company in Canada for just over 20 years. What makes this line so unique? We, as a company are a partner in this line and control exclusive distribution for the entire country. We have a strong influence over any new product that goes into the line and we also have a tech team that participates in a rigorous evaluation process before any new product is introduced into the line. Should there be any reservations or concerns on a product during the testing procedure that introduction is put on hold until our tech team is completely satisfied.</p>
	<p>From its inception the 5-Star philosophy was to offer a quality product at a value price point, we never plan on being the cheapest but we always want to offer the best quality we can, quality that will compete with the markets best. Over the years we have enjoyed great success introducing products with unique characteristics, and strive to be ahead of our competitors in product offerings. From the early days when 5-Star was one of the first alternative brands in the marketplace we now find our line is one of the most recognized alternative lines in North America and we are aware of competitors trying to copy some of the great products we have launched.</p>
	<p>This truly is a line that our company can be proud of, More information can be found at <a href="http://www.autobodybrands.com" target="_blank">www.autobodybrands.com</a></p>
</div>