<div class="news">
	<h5>Color Compass Health</h5>
	<p><strong>9 Tips for Happier and Healthier Living</strong></p>
	<ol>
		<li>Eat "primally" Common sense dictates that the best diet is one based on foods we've been eating the longest in terms of our time on this planet. These are the foods that we’ve evolved to eat and are best adapted to. Studies show that a ‘primal’ diet made up of fruits, vegetables, nuts and seeds, as well as meat, fish and eggs, is best for weight control and improvement in risk markers for illnesses, such as heart disease and diabetes. This ‘go primal’ food philosophy will enable you to cut through the marketing hype and dietary misinformation, and allow you to make healthy food choices quickly and confidently.</li>
		<li>Keep hydrated Water makes up two-thirds of the body and performs a plethora of functions, including acting as a solvent, carrier of nutrients, temperature regulator and body detoxifier. Maintaining hydration can have a profound influence on our vitality and energy levels, including mental alertness.</li>
		<li>Eat mindfully In our fast-paced world, there can be a tendency to eat while distracted and shovel in more food than we need and, at the same time, miss out on culinary pleasure. Many of us will benefit from eating mindfully. Some things to think about here are avoiding eating when distracted, eating more slowly, and taking time to taste food properly. One particular thing to focus on is chewing your food thoroughly – not only does this help us savour food, it also assists the digestive process.</li>
		<li>Get plenty of sunlight, even in the winter! Sunlight, and the vitamin D this can make in the skin, is associated with a wide spectrum of benefits for the body including a reduced risk of several forms of cancer, heart disease, multiple sclerosis and osteoporosis, as well as improved immune function. As a rule of thumb, vitamin D is made when our shadow is shorter than our body length, ie when the sun is high in the sky. While burning is to be avoided, get as much sunlight exposure as possible for optimal health. Even when it’s cold outside, it pays to get some external light exposure in the winter, say during lunchtime. Another option is to invest in a sunlight-simulating device and use this daily from October through to March.</li>
		<li>Get enough sleep, Sleep has the ability to optimize mental and physical energy, and optimal levels of sleep (about eight hours a night) are linked with reduced risk of chronic disease and improved longevity. One simple strategy that can help ensure you get optimal amounts of sleep is to go to bed earlier. Getting into bed by 10pm or 10.30pm is a potentially useful investment in terms of your short- and long-term health and wellbeing. Shutting down the computer or turning off the TV early in the evening is often all it takes to create the time and space for earlier sleep.</li>
		<li>Walk regularly Aerobic exercise, including something as uncomplicated and low-impact as walking, is associated with a variety of benefits for the body and the brain, including a reduced risk of chronic diseases, anti-anxiety and mood-enhancing effects. Aim for a total of about 30 minutes of brisk walking every day.</li>
		<li>Engage in some resistance exercise Resistance exercise helps to maintain muscle mass and strengthens the body. This has particular relevance as we age, as it reduces the risk of disability and falls. Many highly useful exercises can be done at home, such as press-ups, sit-ups and squats. Invest in a Dyna-Band or dumbbells to extend your home routine to other exercises, too.</li>
		<li>Practice random acts of kindness Random acts of kindness are good for givers and receivers alike. It could be a quick call or text to someone you care about or have lost touch with, or showing a fellow motorist some consideration, or giving up your seat on a train or bus, or buying someone lunch or giving a spontaneous bunch of flowers.</li>
		<li>Practice the art of appreciation Modern-day living tends to be aspirational and we can easily find ourselves chasing an ever-growing list of goals, many of which can be material. Some of us could do with spending more time not focusing on what we don’t have, but on what we do. Our mood can be lifted by giving thanks for anything from our friends and family to a beautiful landscape or sunset.</li>
	</ol>
	<p>Congratulations to Al Watts who correctly responded along with ten others (great odds!) to last month's Color Compass Health giveaway, the answer was Cortisol.</p>
	<p>Reply back this month with one benefit to staying hydrated to enter a random draw for a $50 Safeway gift card, and a 21 oz Hyrdo Flask.<br>
		<a href="mailto:connected@colorcompass.com">connected@colorcompass.com</a></p>
</div>