<div class="news">
	<h5>Coquitlam Training Centre will be Breaking Ground Soon!</h5>
	<p>In just two short weeks a new Color Compass training centre will break ground at our Coquitlam BC distribution centre and office. Currently the Coquitlam location is the head office for White & Peters, PBE Distributors, CCC Accounts Receivable, IT, and Marketing. Once completed the new training centre will bring the total number to four for the Color Compass group throughout Western Canada, something that in our industry is unheard of! </p>
	<div class="image">
		<img src="/images/news/coquitlam-training-centre.jpg" alt="Coquitlam Training Centre">
	</div>
	<p>We sat down with the General Manager of White & Peters Mort Hall recently to discuss the new  centre, "Both Tim Shay and I are very pleased to announce that we are breaking ground on the BC Color Compass Training  Center on November 15, the project will be in 2 stages, the initial stage will see the installation of a Global Ultra down draft spray booth and also an open face booth for test panels.  With the addition of this spray booth we will be able to provide all of the required training for our AKZO, BASF and other paint brand training."</p>
	<p>As the complexity of vehicle repairs increase so must the equipment and training, something that this new facility and all of the CCC training facilities are ready for. Mort alluded to these upgrades, "The electrical will be upgraded so as we have the ability to fully use and train on the advanced  Pro Spot welders and equipment that we sell, as well as many other equipment brands that we now have and will be adding in the near future. The second stage will see us build  a state of the art classroom on the lower level of the building, with this we can then offer a multitude of Color Compass University training for ourselves and our customers, such as I-CAR, Dale Carnegie and a variety of other valuable training that will assist Color Compass in maintaining our status as a premier supplier in our industry."</p>
	<p>We look forward to sharing more on the new facility, and marketing the power that having four advanced training centre's will have in our industry.</p>
</div>
