<div class="news">
	<h5>White &amp; Peters Customer Has Rare Certification</h5>
	<div class="image">
		<img src="/images/richmond-auto-body.jpg" alt="Customer Has Rare Certification">
	</div>
	<p>Lamborghini's vehicles are some of the highest-priced in the world and the complexity of their construction reflects the sticker price. A total of two shops in all of Canada have been granted the exclusive rights to perform collision repairs on Lamborghinis in this country.</p>
	<p>CSN-427 Auto Collision in Toronto and CSN-OpenRoad Richmond Auto Body are the facilities in question. Achieving the authorization from Automobili Lamborghini Canada to perform these repairs was no easy task. An extensive audit process, training and specialized equipment requirements had to be me by these facilities before certification, due in large part to the complexity of the technology needed to check the integrity of the carbon fibre monocoque and aluminum present in the new models.</p>
	<p>"A 45-year commitment to collision repairs means we're not satisfied until we've mastered collision repairs for every make, model and innovative advancement set forth by today's vehicle manufacturers," says Lorenzo D'Alessandro, President of CSN-427 Auto Collision and Founding Director of CSN Collision Centres. "Becoming Lamborghini Factory Certified is both an honour and a proud accomplishment for our team of dedicated collision repair specialists."</p>
	<p>Lamborghini takes repairs to its vehicles very seriously. In fact, when the company introduced the Aventador LP700-4 in 2011, all vehicles to be repaired had to be sent not to the dealership, but to a special facility outside Seattle, the Automobili Lamborghini Advanced Composite Structures Laboratory (ACSL). At that point, a call would go out to one of Lamborghini's special "flying doctors", specialist technicians with the tools and training needed for extensive carbon fiber repairs. At that time, there was only one "flying doctor" for all of North America.</p>
	<p>"For over 55 years we have striven to provide industry leading quality, service and innovation in collision repair", says Randy Lowe, President of CSN-OpenRoad Richmond Auto Body. "OEM certification is the future of the collision industry and we will continue to invest in the best technicians, equipment and facilities. We are proud to add the iconic Lamborghini brand to our list of certifications and will uphold their name with every repair."</p>
	<p>Both facilities are long-standing family owned and operated businesses with multiple original equipment manufacturer certifications for both aluminum and steel repairs. Both CSN-427 Auto Collision and CSN-Open Road Richmond Auto Body are members of CSN Collision Centres</p>
	<em>- Collision Repair Magazine</em>
</div>